#!/usr/bin/env bash
#ckage list to make sure you have the latest package information

sudo apt update
sudo apt -y install nginx
sudo chown -r "$user":"$user"
sudo chmod -R 755 var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
