#!/usr/bin/env bash
# pleaseeeeee workkkkkkk

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
