#!/usr/bin/env bash
#ckage list to make sure you have the latest package information
apt-get update
apt-get install -y nginx

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        echo 'Hello World!';
    }
}" > /var/www/html/index.nginx-debian.html
kill -s HUP $(cat /var/run/nginx.pid)
if ! pgrep -x "nginx" >/dev/null; then
    echo "Nginx failed to start."
    exit 1
fi
apt-get autoremove -y
apt-get clean

echo "Nginx is installed and configured. It should be listening on port 80."
