#!/usr/bin/env bash
#how gbt bunkfs jdefv

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index
string_for_replacement="service_name _;\n\trewrite ^\/redirect_me https:\/\/.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/$string_for_replacement/" /etc/nginx/site-enabled/default
sudo service nginx restart
